# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
